services:
  gateway:
    image: gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      ACTIVE_PROFILE: prod
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    restart: "no"
    command:
      - "start-dev"
    ports:
      - "9080:9080"
    depends_on:
      - kc-postgres
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: kc-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak-db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres_secret
      KC_HEALTH_ENABLED: "true"
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    healthcheck:
      test:
        [ "CMD-SHELL", "{ exec 3<>/dev/tcp/localhost/9000 && echo -e \"GET /health/ready HTTP/1.1\nhost: localhost:9000\n\" >&3 && timeout --preserve-status 1 cat <&3 | grep -m 1 -q 'status.*UP'; }" ]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    networks:
      - keycloak-network
      - internal-kc-network

  kc-postgres:
    image: postgres:17.2
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - kc-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secret
      POSTGRES_DB: keycloak-db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - internal-kc-network

volumes:
  kc-postgres_data:

networks:
  internal-kc-network:
    driver: bridge
  keycloak-network:
    driver: bridge
  app-network:
    driver: bridge