spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/task-tamer
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: task-tamer-rest-api
      principle-attribute: preferred_username
    keycloak:
      client-url: http://localhost:9080/realms/task-tamer/protocol/openid-connect/
      client-id: task-tamer-rest-api
      client-secret: GsCfC7K1PeIxZxfVlTThv33FwtjUdJ48
      redirect-url: http://localhost:3000