spring:
  port: 8082
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: UI
            provider: keycloak
            client-secret: VCY9aaCeTUFcdKEzTVN36e4BlD60CPtm
            client-name: KEYCLOAK
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9080/realms/task-tamer